<?php
	
				$LANG = array(
		
				# GROUPES
				'L_GROUPE_SPXWBOOKMARKET_TITLE'			=> 'Bookmarket',
				
				
				
				# TABLE
					'L_TABLE_SPXWBOOKMARKET_TITLE'			=> 'Bookmarket',
					'L_TABLE_SPXWBOOKMARKET_DESCRIPTION'	=> '<p>Administration of your bookmarket.</p>',
					# ACTION TITLE
					'L_TABLE_SPXWBOOKMARKET_ACTIONTITLE'	=> '',
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKET_TITLE_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_TITLE_TITLE'			=> 'Title',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_TITLE_HELP'	=> '',
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKET_DATE_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_DATE_TITLE'			=> 'Date',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_DATE_HELP'	=> '',
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKET_URL_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_URL_TITLE'			=> 'Url',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_URL_HELP'	=> '',
					
				
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKET_ACTIF_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_ACTIF_TITLE'			=> 'Active',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_ACTIF_HELP'	=> '',
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKET_CONTENT_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_CONTENT_TITLE'			=> 'Text',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_CONTENT_HELP'	=> '',
						
				
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKET_KEYWORD_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_KEYWORD_TITLE'			=> 'Keywords',
						'L_TABLE_COLUMN_SPXWBOOKMARKET_KEYWORD_HELP'	=> '',
						
				
				
				# TABLE
					'L_TABLE_SPXWBOOKMARKETKEYWORD_TITLE'			=> 'Keywords',
					'L_TABLE_SPXWBOOKMARKETKEYWORD_DESCRIPTION'	=> '<p>Keywords administration.</p>',
					# ACTION TITLE
					'L_TABLE_SPXWBOOKMARKETKEYWORD_ACTIONTITLE'	=> '',
					# COLUMN 
						'L_TABLE_COLUMN_SPXWBOOKMARKETKEYWORD_TITLE_HIGHLIGHTTITLE'			=> '',
						'L_TABLE_COLUMN_SPXWBOOKMARKETKEYWORD_TITLE_TITLE'			=> 'Title',
						'L_TABLE_COLUMN_SPXWBOOKMARKETKEYWORD_HELP'	=> '',
					
					
					
				
						
				);
				?>